name: env install with mamba

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9] #["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: binette_dev.yaml
    - name: Install checkm2 from github
      run: |
        wget https://github.com/chklovski/CheckM2/archive/refs/tags/1.0.1.tar.gz
        tar -xf 1.0.1.tar.gz
        rm 1.0.1.tar.gz
        pip install CheckM2-1.0.1/

